### ISSUE TITLE
Python3 support ?

### ISSUE THREAD

**Issue by maks-us** [google/google-visualization-python#38]
Collecting https://github.com/google/google-visualization-python/zipball/master (from -r requirements.txt (line 9))
  Downloading https://github.com/google/google-visualization-python/zipball/master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/94/_b72550n6x9bbrdcdw7w694m0000gn/T/pip-xi2ugjee-build/setup.py", line 23, in <module>
        import gviz_api_test
      File "/private/var/folders/94/_b72550n6x9bbrdcdw7w694m0000gn/T/pip-xi2ugjee-build/gviz_api_test.py", line 30, in <module>
        from gviz_api import DataTable
      File "/private/var/folders/94/_b72550n6x9bbrdcdw7w694m0000gn/T/pip-xi2ugjee-build/gviz_api.py", line 30, in <module>
        import cStringIO
    ModuleNotFoundError: No module named 'cStringIO'

**Comment by pl77** [comment]
The gviz_api supports some very old python versions which made writing a single py3 version tricky.  I built a py2.7/py3 version and created a pull request but I don't know if google is actively maintaining this repo anymore.  You can find my py3 file in the pull requests.

**Comment by mishas** [comment]
This is now fixed in #40

**Comment by mishas** [comment]
This is now closed in #40
